### ISSUE TITLE
Transitive dependencies with classifier are not downloaded

### ISSUE THREAD

**Issue by joan38** [coursier/coursier#1386]
From issue https://github.com/sbt/sbt/issues/5136

## steps
sbt version: 1.3.2

I think I've been able to reproduce this outside of Netflix:
```
libraryDependencies += "io.netty" % "netty" % "3.10.6.Final"
```
Then `show Runtime/fullClasspath` won't show `netty-tcnative` whereas we depend on it in https://repo1.maven.org/maven2/io/netty/netty/3.10.6.Final/netty-3.10.6.Final.pom

## problem

I have a dependency that depends transitively as the following ivy file shows:
```
<dependency org="com.netflix.bdp" name="presto-s3fs" rev="1.3.2" conf="compile->default">
  <artifact xmlns:m="http://ant.apache.org/ivy/maven" name="presto-s3fs" type="jar" ext="jar" m:classifier="core"/>
</dependency>
```
When `useCoursier := true` that transitive dependency is not in the classpath.

## workaround

`useCoursier := false`
or explicitly add:
`("com.netflix.bdp" % "presto-s3fs" % "1.3.2").classifier("core")`

**Comment by alexarchambault** [comment]
@joan38 `io.netty:netty-tcnative:1.1.30.Fork2` (with classifier `windows-x86_64`) is an optional dependency of `io.netty:netty:3.10.6.Final`, so it's expected that it's not pulled by default.

**Comment by joan38** [comment]
Arf yes this one is not a great example.
I found https://github.com/coursier/coursier/issues/320 @tjni do you have a way to reproduce this?

**Comment by joan38** [comment]
@alexarchambault I've been able to reproduce the issue in https://github.com/joan38/sbt-issue-1386

What's happening is that when a classifier is specified in a ivy dependency and that transitive dependency gets resolved from Maven then it doesn't listen to the classifier.

I run `show Runtime/fullClasspath` and the jar `lib2` is not in there.
If I swap around the 2 custom resolvers in the `resolvers` key (put the Maven after Ivy) then it will resolve the transitive dependency from Ivy too and it's all fine.

Let me know if you need anything

**Comment by slandelle** [comment]
Sorry, but it looks like the issue is still here, see https://github.com/sbt/sbt/issues/5325

**Comment by eed3si9n** [comment]
There's also https://github.com/coursier/coursier/issues/1455 that was fixed in Coursier, but not part of sbt.

**Comment by alexarchambault** [comment]
@slandelle It seems there's still an issue when publishing to Ivy repositories from sbt, yes (and then depending on what's been published). Things needs to be fixed on the sbt side now, see https://github.com/sbt/sbt/issues/5325#issuecomment-567711900.
