### ISSUE TITLE
lmcoursier.CoursierDependencyResolution#update should use passed configuration

### ISSUE THREAD

**Issue by OlegYch** [coursier/coursier#1541]
In particular ignoring 'missingOk' causes 'updateClassifiers' sbt task (used by intellij to import projects) to fail in some cases.
The issue was first reported at https://github.com/sbt/sbt/issues/5374

**Comment by OlegYch** [comment]
so, on CI 'sbt-lm-coursier/scripted shared-2/update-sbt-classifiers' fails as expected (https://travis-ci.org/coursier/sbt-coursier/jobs/646427306#L1731) with this change https://github.com/coursier/sbt-coursier/commit/404af50b6d8ee4df7ce7e07406656ebc8cc19575

unfortunately locally it fails with 'assertion failed: Any of WrappedArray((org.scala-lang,scala-library)) not found'
and 'sbt-coursier/scripted shared-2/update-sbt-classifiers' does not fail at all, though it does print 'Found module 		org.webjars:npm:4.2.0:default: (MISSING) Artifact(npm, src, jar, Some(sources), Vector(), Some(https://repo1.maven.org/maven2/org/webjars/npm/4.2.0/npm-4.2.0-sources.jar), Map(), None)'

so i'm not sure how to proceed, it looks like in some cases missing artifact is treated as error and in others it doesn't

**Comment by mikail-khan** [comment]
The only way around this I have found so far is to drop back down to 1.3.6, let the project resolve in terms of deps (or whatever it needs) and then move back up to 1.3.8 :frowning_face:

**Comment by dcsobral** [comment]
This is related to sbt/sbt#5465 and sbt/sbt#5078.

**Comment by andreaTP** [comment]
@dcsobral and @OlegYch thanks a lot for narrowing this error down!
I don't have a fix but just found a workaround:
```
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.0" exclude ("org.webjars", "npm"))
libraryDependencies += "org.webjars" % "npm" % "4.2.0"
```

Basically, excluding from the transitive dependencies of the sbt plugins the offending ones and adding them back as normal `libraryDependencies` make `updateSbtClassifiers` working.

**Comment by hepin1989** [comment]
Yes，Yes even override will not works

**Comment by dcsobral** [comment]
@eed3si9n @alexarchambault I do not believe this issue was fixed by coursier/sbt-coursier#212. It fixed one particular case of `missingOk` flag, but it still does not respect the `updateConfiguration` passed in as a parameter on `update`. This means `retrieve` in `DependencyResolution` is broken, as is the `retrieveManaged` setting and anything else using `RetrieveConfiguration`, as well as other configurations such as artifact filter, offline and, yes, even `missingOk` when used through the `DependencyResolution` API.

The coursier/sbt-coursier#212 "fix" relies entirely on the fact that `updateTask0` passes the value of `updateConfiguration` as a parameter, so it works for the `update`, `updateFull` and `evicted` tasks, but is useless to anything relying on SBT's library management API.  It's a work-around, not a fix.

I don't think this issue should be closed,

**Comment by eed3si9n** [comment]
@dcsobral You're right. My "Fixes" was an overstatement in there.

**Comment by OlegYch** [comment]
@eed3si9n unfortunately this doesn't seem to fix the original problem https://travis-ci.org/github/coursier/sbt-coursier/jobs/683829277#L1036

**Comment by eed3si9n** [comment]
Looks like I handled resolution error (version that doesn't exist) but not fetch error (source file that doesn't exist).

**Comment by dcsobral** [comment]
Can we re-open this issue, at any rate?

**Comment by alexarchambault** [comment]
FYI everyone, coursier considers artifacts from Maven repositories as optional by default. That means if a javadoc or source JAR is missing (with a 404 status), `updateClassifiers` will not fail. There's no need for `missingOk` in most cases thanks to that.

The only case coursier assumes an artifact is mandatory is when explictly asking for a particular artifact type / classifier (https://github.com/coursier/coursier/pull/1470), like
```scala
libraryDependencies += "io.netty" % "netty-transport-native-epoll" % "4.1.44.Final" classifier "linux-x86_64"
```
(POMs are also mandatory during resolution of course…)

**Comment by alexarchambault** [comment]
`updateSbtClassifiers`, in spite of its name, uses (in sbt) a different logic than `updateClassifiers`. It [does rely on explicit artifacts internally](https://github.com/sbt/librarymanagement/blob/3b3aa2f495f579446ebae017fb70ca9d76eb9512/core/src/main/scala/sbt/librarymanagement/DependencyResolution.scala#L195) (this method ends up being used for `updateSbtClassifiers`, and not `updateClassifiers`, in spite of its name). That made `updateSbtClassifiers` fail in some cases since https://github.com/coursier/coursier/pull/1470, hence the errors you're seeing here.

**Comment by alexarchambault** [comment]
Also note that [some logic in sbt](https://github.com/sbt/sbt/blob/f1370a25feb723e0da1d205b83eae93448595ca2/main/src/main/scala/sbt/internal/LibraryManagement.scala#L318-L340) used by `updateSbtClassifiers` makes it remember artifacts it failed to download. If a first attempt of `updateSbtClassifiers` failed, that logic makes the subsequent attempts… succeed. This logic puts files under `~/.ivy2`, and doesn't pay attention to `sbt.ivy.home`. So it also makes scripted tests fail their first attempt, then succeed in the subsequent ones. Hence the [apparent transient](https://github.com/coursier/sbt-coursier/pull/223) character of these errors.

**Comment by alexarchambault** [comment]
Should be fixed by https://github.com/coursier/sbt-coursier/pull/235.

**Comment by dcsobral** [comment]
This didn't fix other configurations passed to `DependencyResolution`, did it? If not, I ought to create another issue to track other problems.
