### ISSUE TITLE
Can't install scala-cli or cs on aarch64 architecture

### ISSUE THREAD

**Issue by carlosedp** [coursier/coursier#2537]
This is issue is now an umbrella issue about aarch64 support. Please see also #2614 and #2516.

---

I'm not sure this should be opened here but while trying to install scala-cli using coursier on an ARM64 (aarch64) host, I get:

```
❯ cs install scala-cli
https://repo1.maven.org/maven2/org/virtuslab/scala-cli/cli_3/maven-metadata.xml
  No new update since 2022-09-13 13:14:45
https://repo1.maven.org/maven2/com/google/code/gson/gson/maven-metadata.xml
  No new update since 2022-07-31 18:29:36
Exception in thread "main" coursier.jvm.JvmCache$JvmNotFoundInIndex: JVM graalvm:19.3 not found in index: JVM graalvm not found
	at coursier.jvm.JvmCache.$anonfun$getIfInstalled$1(JvmCache.scala:35)
	at coursier.jvm.JvmCache.$anonfun$getIfInstalled$1$adapted(JvmCache.scala:34)
	at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
	at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
	at coursier.util.Task$.wrap(Task.scala:82)
	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
❯ which java
/home/carlosedp/.cache/coursier/arc/https/github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.2.0/graalvm-ce-java17-linux-aarch64-22.2.0.tar.gz/graalvm-ce-java17-22.2.0/bin/java
❯ java -version
openjdk version "17.0.4" 2022-07-19
OpenJDK Runtime Environment GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06)
OpenJDK 64-Bit Server VM GraalVM CE 22.2.0 (build 17.0.4+8-jvmci-22.2-b06, mixed mode, sharing)

❯ uname -a
Linux corellia 5.19.0-15-generic #15-Ubuntu SMP PREEMPT_DYNAMIC Tue Aug 2 07:45:33 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

❯ cs list
amm
bloop-jvm
cs
g8
mdoc
mill
sbt
scala
scalafix
scalafmt
```

As seen I already have some other tools installed thru cs and GraalVM properly set.

**Comment by SethTisue** [comment]
I'm extremely interested in knowing how to resolve this.

**Comment by carlosedp** [comment]
I've successfully built scala-cli on arm64 from source btw... but on `cs` ... dunno :)

**Comment by SethTisue** [comment]
I found a workaround: if I set `JAVA_HOME` to point to Java 8 instead of 17 before running `coursier install scala-cli`, I don't get the error.

**Comment by SethTisue** [comment]
yes

**Comment by SethTisue** [comment]
Is this supposed to be fixed effectively immediately, or do I need to wait for the next release of coursier? (Asking because I see the fix was in coursier/apps, so I might have been expected that to take effect immediately?)

**Comment by carlosedp** [comment]
The issue is originally related to aarch64 (ARM64) on Linux and the linked PR added the binary for Darwin aarch64.

**Comment by mkurz** [comment]
I guess this needs to be re-opened. Would be nice to make this work on aarch64 on Linux (I do use Asahi Linux on my M1)

**Comment by carlosedp** [comment]
As I commented on #174, I can provide a scala-cli binary for Linux/aarch64 if needed.

**Comment by carlosedp** [comment]
Ping... I think this should be reopened.

**Comment by okennedy** [comment]
I'm having a comparable issue on Linux/ARM.

**Comment by julienrf** [comment]
Re-opening because I see many issues related to the aarch64 architecture support (#2514, #2616).

**Comment by julienrf** [comment]
I think a similar problem has been solved in Scala CLI (see https://github.com/VirtusLab/scala-cli/issues/1279). I am pinging @lwronski to see if he can guide us toward a solution here, based on his experience with Scala CLI.

**Comment by tgodzik** [comment]
Wasn't this issue about aarch64 support on linux? That seems to be available here: https://github.com/coursier/coursier/releases/download/v2.1.0-RC2/cs-aarch64-pc-linux.gz

What we are still missing is M1 binary, but that requires some work on setting up M1 machines.

**Comment by okennedy** [comment]
The binary exists, but continues to fail on `setup` or `install scalac` due to a missing graal build for the platform.  My understanding is that graal only publishes ARM builds for later versions.  I'm not sure why graal needs to be a dependency... would it be possible to (temporarily) remove it in the arm build?

```
$ ./cs setup
Checking if a JVM is installed
Found a JVM installed under /usr/lib/jvm/java-11-openjdk-arm64.

Checking if ~/.local/share/coursier/bin is in PATH

Checking if the standard Scala applications are installed
  Found ammonite
  Found cs
  Found coursier
  Found scala
  Found scalac
JVM graalvm:19.3 not found in index: JVM graalvm not found
```

**Comment by lwronski** [comment]
@carlosedp @okennedy  Can you try to install scala-cli in this way:
```
cs install scala-cli --graalvm-default-version https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.2.0/graalvm-ce-java17-darwin-aarch64-22.2.0.tar.gz
```

It uses Graalvm JVM 17  for M1.

**Comment by okennedy** [comment]
Looks like a coursier bug (adding a graalvm prefix to the URL and not removing it at download time)

```
$ ./cs install scala-cli --graalvm-default-version https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.2.0/graalvm-ce-java17-darwin-aarch64-22.2.0.tar.gz
[ ... lots of repo downloads ]
Exception in thread "main" java.net.MalformedURLException: URL graalvm:https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.2.0/graalvm-ce-java17-darwin-aarch64-22.2.0.tar.gz doesn't contain an absolute path
```

**Comment by lwronski** [comment]
@okennedy yes, that looks like a bug. 

Can you try running scala-cli install with the following parameters?: 
```
cs install scala-cli --graalvm-default-version 22.3.0
```

I believe this should work since [jvm-index.json](https://github.com/coursier/jvm-index/blob/master/index.json#L1467) has graalvm in versions 22.1.0, 22.2.0 and 22.3.0 listed for M1.

**Comment by okennedy** [comment]
For reference, this isn't on an M1.  It's an NXP i.MX 8M.  Here's `uname -srvmo`
```
Linux 6.0.0-1-librem5 #1 SMP PREEMPT Tue Nov 15 21:27:04 UTC 2022 aarch64 GNU/Linux
```

22.3.0 is listed under arm64 for linux as well, so probably not the issue.  `uname` does reports `aarch64` and not `arm64`.  Could that be part of the problem?

**Comment by lwronski** [comment]
```
```

**Comment by lwronski** [comment]
@carlosedp @okennedy Can you try again to install `scala-cli` via `cs`? 
It should be fixed by https://github.com/coursier/apps/pull/191 and https://github.com/VirtusLab/scala-cli/pull/1703.

**Comment by carlosedp** [comment]
Just tried after updating coursier to 2.1.3-RC3 but still not able to install on Linux / Aarch64:

```
❯ cs version
2.1.0-RC3-1
❯ cs install scala-cli
https://repo1.maven.org/maven2/org/virtuslab/scala-cli/cli_3/maven-metadata.xml
  No new update since 2022-12-19 14:47:41
https://repo1.maven.org/maven2/com/google/code/gson/gson/maven-metadata.xml
  No new update since 2022-10-25 01:12:54
Exception in thread "main" coursier.jvm.JvmCache$JvmNotFoundInIndex: JVM graalvm:19.3 not found in index: JVM graalvm not found
	at coursier.jvm.JvmCache.$anonfun$getIfInstalled$1(JvmCache.scala:35)
	at coursier.jvm.JvmCache.$anonfun$getIfInstalled$1$adapted(JvmCache.scala:34)
	at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
	at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
	at coursier.util.Task$.wrap(Task.scala:82)
	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
❯ cs install scala-cli --graalvm-default-version 22.2.0
https://repo1.maven.org/maven2/org/virtuslab/scala-cli/cli_3/maven-metadata.xml
  No new update since 2022-12-19 14:47:41
https://repo1.maven.org/maven2/com/google/code/gson/gson/maven-metadata.xml
  No new update since 2022-10-25 01:12:54
Exception in thread "main" coursier.jvm.JvmCache$JvmNotFoundInIndex: JVM graalvm:22.2.0 not found in index: JVM graalvm not found
	at coursier.jvm.JvmCache.$anonfun$getIfInstalled$1(JvmCache.scala:35)
	at coursier.jvm.JvmCache.$anonfun$getIfInstalled$1$adapted(JvmCache.scala:34)
	at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
	at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
	at coursier.util.Task$.wrap(Task.scala:82)
	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
```

**Comment by lwronski** [comment]
@carlosedp Thanks for checking, I missed that `coursier/apps` should be also released with my changes - https://github.com/coursier/apps/releases/tag/v1.0.35.

Now it should work since `coursier/apps` was released.

I tested it in Ubuntu / Aarch64

```
$ ./cs-aarch64-pc-linux version
2.1.0-RC3-1
$ ./cs-aarch64-pc-linux install scala-cli
https://repo1.maven.org/maven2/io/get-coursier/apps/maven-metadata.xml
  100.0% [##########] 2.6 KiB (44.0 KiB / s)
Wrote scala-cli
Warning: /root/.local/share/coursier/bin is not in your PATH
To fix that, add the following line to ~/.bashrc

export PATH="$PATH:/root/.local/share/coursier/bin"
```

**Comment by mkurz** [comment]
If you run coursier on Linux with an aarch64 kernel, and your kernel page size is not 4k, you might be interested in [this comment](https://github.com/coursier/coursier/issues/2636#issuecomment-1363491391).
For me I have a page size that is not 4k but 16k:
```sh
$ getconf PAGESIZE
16384
```
That might be the case too if you run Linux in an virtual machine in macOs on a Apple Silicon machine.

**Comment by james-johnston-thumbtack** [comment]
I am also unable to setup cs on a clean macOS computer with Apple M1 Pro silicon running Ventura 13.2.

First, I installed Azul Zulu 8.68.0.21-CA-macos-aarch64 ---- this is a JDK 8 that is compiled natively for aarch64.  Many other JDK 8 builds only provide x64 which is why I installed Zulu.  I used the older JDK 8 because (1) unfortunately we still use it in production, (2) it's the documented default for Coursier (and therefore should be expected to work).

Next, I tried manually setting up Coursier, which fails with a mysterious "No main class found".  These instructions were run today a few minutes ago:
```
# Following instructions from https://get-coursier.io/docs/cli-installation
% curl -fL https://github.com/VirtusLab/coursier-m1/releases/latest/download/cs-aarch64-apple-darwin.gz | gzip -d > cs
% chmod +x cs
% ./cs version
2.1.0-RC5
% ./cs setup
Checking if a JVM is installed
Found a JVM installed under /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home.

Checking if ~/Library/Application Support/Coursier/bin is in PATH
  Should we add ~/Library/Application Support/Coursier/bin to your PATH via ~/.profile, ~/.zprofile? [Y/n] y

Checking if the standard Scala applications are installed
  Installed ammonite
  Installed cs
  Installed coursier
  Installed scala
  Installed scalac
  Installed scala-cli
  Installed sbt
No main class found
```

Here is an abridged version of verbose output, indicating that sbtn is at fault:

```
<snip other successful apps>
Found app sbtn in channel io.get-coursier:apps
Checking prebuilt launcher at https://github.com/sbt/sbt/releases/download/v1.8.2/sbt-1.8.2.zip
Found prebuilt launcher at https://github.com/sbt/sbt/releases/download/v1.8.2/sbt-1.8.2.zip (96B)
Checking prebuilt launcher at https://github.com/sbt/sbt/releases/download/v1.8.2/sbt-1.8.2.zip
Found prebuilt launcher at https://github.com/sbt/sbt/releases/download/v1.8.2/sbt-1.8.2.zip (96B)
Checking prebuilt launcher at https://github.com/sbt/sbt/releases/download/v1.8.1/sbt-1.8.1.zip
Found prebuilt launcher at https://github.com/sbt/sbt/releases/download/v1.8.1/sbt-1.8.1.zip (96B)
Checking prebuilt launcher at https://github.com/sbt/sbt/releases/download/v1.8.0/sbt-1.8.0.zip
Found prebuilt launcher at https://github.com/sbt/sbt/releases/download/v1.8.0/sbt-1.8.0.zip (96B)
Checking prebuilt launcher at https://github.com/sbt/sbt/releases/download/v1.7.3/sbt-1.7.3.zip
Found prebuilt launcher at https://github.com/sbt/sbt/releases/download/v1.7.3/sbt-1.7.3.zip (96B)
Got 83 artifacts:
<snip long list>
Found 5 main classes:
  ((,jansi),org.fusesource.jansi.AnsiMain)
  ((org.scala-sbt,Command),sbt.internal.client.NetworkClient)
  ((org.scala-sbt.jline,jline),jline.console.internal.ConsoleRunner)
  ((org.scala-sbt,Test Agent),sbt.ForkMain)
  ((,Java Native Access (JNA)),com.sun.jna.Native)
Exception in thread "main" coursier.install.error.NoMainClassFound: No main class found
	at coursier.install.InstallDir.$anonfun$createOrUpdate$13(InstallDir.scala:307)
	at scala.Option.getOrElse(Option.scala:189)
	at coursier.install.InstallDir.mainClass$lzycompute$1(InstallDir.scala:307)
	at coursier.install.InstallDir.mainClass$1(InstallDir.scala:293)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$14(InstallDir.scala:339)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$14$adapted(InstallDir.scala:311)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$22(InstallDir.scala:417)
	at coursier.install.InstallDir.$anonfun$createOrUpdate$22$adapted(InstallDir.scala:416)
	at coursier.install.Updatable$.get$1(Updatable.scala:61)
	at coursier.install.Updatable$.$anonfun$writing$1(Updatable.scala:106)
	at coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:73)
	at coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:93)
	at coursier.install.Updatable$.writing(Updatable.scala:106)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:416)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:96)
	at coursier.install.InstallDir.createOrUpdate(InstallDir.scala:71)
	at coursier.cli.setup.MaybeInstallApps.$anonfun$task$3(MaybeInstallApps.scala:22)
	at coursier.util.Task$.wrap(Task.scala:82)
	at coursier.util.Task$.$anonfun$delay$2(Task.scala:47)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
```

**Comment by julienrf** [comment]
Thank you for the report. That confirms my analysis here: https://github.com/VirtusLab/coursier-m1/pull/28#issuecomment-1406564806

Could you please confirm that you can run the binary `bin/sbtn-x86_64-apple-darwin` from the latest [release of sbt](https://github.com/sbt/sbt/releases/download/v1.8.2/sbt-1.8.2.zip)?

**Comment by james-johnston-thumbtack** [comment]
> Could you please confirm that you can run the binary `bin/sbtn-x86_64-apple-darwin` from the latest [release of sbt](https://github.com/sbt/sbt/releases/download/v1.8.2/sbt-1.8.2.zip) on your M1?

I downloaded the linked ZIP, unzipped it, and ran the specified binary.  It runs fine:
```
<snip>
[info] welcome to sbt 1.8.2 (Azul Systems, Inc. Java 11.0.18)
<snip>
```

HOWEVER, it's being emulated:
<img width="772" alt="Screenshot 2023-01-27 at 2 16 16 PM" src="https://user-images.githubusercontent.com/22308682/215216166-3f0fe203-d742-4f4e-969e-e00915dbbc05.png">

So the claim at https://github.com/sbt/sbt/issues/7143#issuecomment-1406643734 that this is a universal binary doesn't seem to hold true to me.

**Comment by julienrf** [comment]
If we _can_ run those binaries on aarch64, I think we could go that way for now, unless there are drawbacks in this “emulation” mode?

**Comment by carlosedp** [comment]
Reporting that I just tested using coursier 2.1.0-RC4 I was able to install scala-cli correctly on **Linux/aarch64**:

```
❯ cs version
2.1.0-RC4

❯ scala-cli version
Scala CLI version: 0.1.20
Scala version (default): 3.2.2
```

Thanks!

**Comment by fsvehla** [comment]
> If we _can_ run those binaries on aarch64, I think we could go that way for now, unless there are drawbacks in this “emulation” mode?

It’s much slower than running aarch64 code natively.

**Comment by okennedy** [comment]
> If we _can_ run those binaries on aarch64, I think we could go that way for now, unless there are drawbacks in this “emulation” mode?

Not every ARM system has an emulation layer (e.g., ARM linux can't run x86 binaries)

**Comment by SethTisue** [comment]
I'm not currently able to reproduce this on my Mac 🎉

**Comment by julienrf** [comment]
I was able to run `cs setup` on a Macbook M1 but I had to run `cs setup --jvm 17` for it to succeed (otherwise I hit https://github.com/coursier/coursier/issues/2678#issue-1560699256).

I am closing this issue since the support for aarch64 architecture is done. Please open a new issue if you hit another edge case that is not well covered.

**Comment by SujithaG** [comment]
@julienrf  Could you please help me here
I am getting an error during cs setup 
Checking if the standard Scala applications are installed
  Found ammonite
  Found cs
  Found coursier
  Found scala
  Found scalac
  Found scala-cli
  Found sbt
No main class found

With "cs setup --jvm 17"  
Checking if a JVM is installed
Exception in thread "main" java.lang.Exception: Error while getting https://github.com/coursier/jvm-index/raw/master/index.json: download error: Caught javax.net.ssl.SSLHandshakeException (PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) while downloading https://github.com/coursier/jvm-index/raw/master/index.json
	at coursier.jvm.JvmIndex$.$anonfun$load$5(JvmIndex.scala:142)
	at coursier.jvm.JvmIndex$.$anonfun$load$5$adapted(JvmIndex.scala:140)
	at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
	at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
	at coursier.util.Task$.wrap(Task.scala:82)
	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)

**Comment by julienrf** [comment]
Unfortunately, I cannot spend time on this problem. Have you tried the answers proposed here? https://stackoverflow.com/questions/6659360/how-to-solve-javax-net-ssl-sslhandshakeexception-error
